import React from 'react'

const Text = () => {
  return (
    <div style={{textAlign:"center"}}>
        <h2>Text Componenet</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci aliquam voluptas itaque nam harum voluptates dolorum quaerat possimus magnam consequatur animi illo, nulla perferendis vero veniam officiis. Aliquid aperiam ipsa ipsum consectetur nemo error sapiente maxime! Magni magnam, quo deleniti incidunt error aut nesciunt dolorem nihil enim neque beatae voluptatibus ipsum alias quidem natus laudantium quis molestiae nulla nostrum. Minus aliquid et quas impedit dolorum odit accusantium quidem soluta? Ab sit perspiciatis laudantium neque similique aliquam totam corrupti porro, sint dolorem saepe facere molestiae ratione voluptas cum quaerat quod ea odio numquam quae vel praesentium, repudiandae possimus. Aut magnam ab soluta consequatur explicabo ipsum saepe! Quaerat placeat accusamus ipsam hic excepturi libero aperiam necessitatibus animi sit ipsa voluptatem labore provident voluptatibus non obcaecati laudantium nemo, quis voluptates odit! Quaerat doloremque blanditiis cupiditate soluta repudiandae, maxime eius ducimus laboriosam! Id, tempora officia minima, harum quod impedit facilis maxime accusantium itaque iusto molestias corrupti soluta expedita odit qui repellendus quis laudantium enim nostrum suscipit consequatur velit quas ex quaerat? Itaque voluptatibus ab ipsa corrupti iure consequuntur at eveniet porro impedit repellendus saepe excepturi laudantium autem adipisci exercitationem, voluptatum ducimus repellat voluptatem quod? Aspernatur unde saepe dolorem veniam praesentium aperiam doloremque excepturi reiciendis!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum eligendi nemo explicabo enim eveniet quia architecto! Repudiandae reprehenderit enim quasi exercitationem vitae iste nam dignissimos veniam, doloremque dolor facere optio eaque? Quas sint unde aperiam nulla minus necessitatibus quaerat nobis quam, fuga impedit aliquid excepturi inventore ab dolorem incidunt cupiditate obcaecati non sed ad vero voluptatibus officia perferendis labore. Incidunt quo sequi voluptatem pariatur quia. Veritatis eius nobis totam culpa esse cupiditate rem tenetur libero, accusantium animi non nam quis veniam suscipit expedita doloribus soluta maiores numquam nihil sapiente ab. Unde illum vitae sunt, at aliquam hic saepe odit corporis.</p>
    </div>
  )
}

export default Text